# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 1 List Drafts
GET http://{{host}}/{{base_v3}}/projects/{{project_id}}/workflow-drafts
x-ads-token-data: {{ads_token_data}}
x-ads-gateway-secret: {{ads_gateway_sec}}
Content-Type: application/json

# 171dc62f-63b0-4f84-a4b9-200d09082d97
# 5c5e04af-cbaa-446f-b487-e327a2526cba
###

# 2 Get a Draft
GET http://{{host}}/{{base_v3}}/projects/{{project_id}}/workflow-drafts/{{drafts_id}}
x-ads-token-data: {{ads_token_data}}
x-ads-gateway-secret: {{ads_gateway_sec}}
Content-Type: application/json

###

# 3 Create a Draft
POST http://{{host}}/{{base_v3}}/projects/{{project_id}}/workflow-drafts
x-ads-token-data: {{ads_token_data}}
x-ads-gateway-secret: {{ads_gateway_sec}}
Content-Type: application/json

{
  "name": "test24ab",
  "templateId": "c97c4087-146b-4152-b32d-a718fcbb7288",
  "description": "The Three Step Approval workflow allows you to:1. Route documents through ",
  "approvalOptions": [
    {
      "id": "b2a3c3b7-4fef-40a4-868b-981b23e7182f",
      "label": "Rejected",
      "value": "rejected",
      "iconValue": "rejected-cross",
      "buildIn": true,
      "labelLocId": "rejected"
    },
    {
      "id": "f44e623d-f04f-47fe-8195-efc43d1d985b",
      "label": "Approved",
      "value": "approved",
      "iconValue": "approved-check",
      "buildIn": true,
      "labelLocId": "approved"
    }
  ],
  "steps": [
    {
      "id": "Lane_1tyn3a9",
      "name": "Initiator",
      "type": "initiator",
      "nameLocId": "initiator",
      "candidates": {
        "roles": [],
        "users":[
          {
            "oxygenId":"U5XCJQ22TL8G"
          }
        ],
        "companies": []
      }
    },
    {
      "id": "Lane_0ecss1f",
      "name": "Reviewer 1",
      "taskName": "Initial Review 1",
      "type": "reviewer",
      "nameLocId": "reviewer1",
      "candidates": {
        "roles": [],
        "users": [
          {
            "oxygenId":"U5XCJQ22TL8G"
          },
          {
            "oxygenId":"9MVAPZMKEKAN"
          }
        ],
        "companies": []
      },
      "duration": 3,
      "groupReview": {
        "enabled": true,
        "maxTaskNumber": 1,
        "completionCondition": 1,
        "meta":{
          "min": 1,
          "type": "minimum"
        }
      }
    },
    {
      "id": "Lane_0p5azmp",
      "name": "Reviewer 2",
      "taskName": "Initial Review 2",
      "type": "reviewer",
      "nameLocId": "reviewer2",
      "candidates": {
        "roles": [],
        "users": [ {
          "oxygenId":"U5XCJQ22TL8G"
        }, {
          "oxygenId": "9MVAPZMKEKAN"
        }],
        "companies": []
      },
      "duration": 3,
      "groupReview": {
        "enabled": true,
        "maxTaskNumber": 2,
        "completionCondition": 2,
        "meta":{
          "type":"minimum"
        }
      }
    },
    {
      "id": "Lane_068sgjq",
      "name": "Approver",
      "taskName": "doc-approver",
      "nameLocId": "approver",
      "candidates": {
        "roles": [],
        "users":[
          {
            "oxygenId":"U5XCJQ22TL8G"
          }
        ],
        "companies": []
      },
      "duration": 3
    }
  ],
  "rules": [{
    "taskId": "Task_1832rge",
    "parameters": {
      "enabled": true,
      "condition": "All",
      "folderUrn": "urn:adsk.wipqa:fs.folder:co.delbQQtfTCCLgDGucz0xAA"
    }
  }],
  "descriptiveLanguage": "Memo"
}

###

# 4 Publish Drafts
POST http://{{host}}/{{base_v3}}/projects/{{project_id}}/workflow-drafts:batch-publish
x-ads-token-data: {{ads_token_data}}
x-ads-gateway-secret: {{ads_gateway_sec}}
Content-Type: application/json

[
  {
    "id": "47f0c60b-36db-4d9a-be7b-a126c8fe4617",
    "name": "test>"
  }
]

###