# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET https://{{host}}/{{base_url}}/containers/{{container_id}}/templates/7175bd3e-32df-11ec-ae52-0242ac110026
Accept: application/json
Authorization: Bearer {{auth_token}}

###